server:
  port: 8080

spring:
  application:
    name: user-service

  config:
    import:
      - optional:env.yml
      - optional:application-oauth.yml
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useSSL=false&serverTimezone=UTC
    username: ${mysql.username}
    password: ${mysql.password}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  #  instance:
  #    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.host.ip}:8761/eureka
    instance:
      hostname: ${service.ip}

greeting:
  message: Welcome to user-service
