server:
  port: 8111

spring:
  application:
    name: my-first-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://43.202.4.152:8761/eureka
  instance:
    hostname: localhost
#    hostname: 52.78.165.51
#    instance-id: 52.78.165.51:8111
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: lb2

server:
  port: 8112

eureka:
  client:
    serviceUrl:
      defaultZone: http://43.202.4.152:8761/eureka
  instance:
    hostname: 52.78.165.51